/*
 * Copyright (c) 2016 Marvell.
 *
 * SPDX-License-Identifier:     BSD-3-Clause
 * https://spdx.org/licenses
 */

#ifndef __OCTEONTX_SDEI_H__
#define __OCTEONTX_SDEI_H__

/* SDEI explicit private event numbers */
#define OCTEONTX_SDEI_RAS_MDC_EVENT		0x40000000
#define OCTEONTX_SDEI_RAS_MCC_EVENT		0x40000001
#define OCTEONTX_SDEI_RAS_LMC_EVENT		0x40000002
#define OCTEONTX_SDEI_RAS_AP0_EVENT		0x40000003
/* reuse existing event numbers from absent components for new */
#define OCTEONTX_SDEI_RAS_DSS_EVENT		OCTEONTX_SDEI_RAS_MCC_EVENT
#define OCTEONTX_SDEI_RAS_TAD_EVENT		OCTEONTX_SDEI_RAS_LMC_EVENT

#define OCTEONTX_SDEI_PRIVATE_EVENTS \
	SDEI_DEFINE_EVENT_0(SDEI_SGI_IRQ), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_MDC_EVENT, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_MCC_EVENT, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_LMC_EVENT, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 1, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 2, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 3, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 4, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 5, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 6, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 7, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 8, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 9, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 10, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 11, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 12, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 13, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 14, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 15, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 16, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 17, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 18, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 19, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 20, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 21, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 22, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_AP0_EVENT + 23, SDEI_MAPF_CRITICAL), \


#define OCTEONTX_SDEI_SHARED_EVENTS

#endif // __OCTEONTX_SDEI_H__
