/*
 * Copyright (C) 2016-2020 Marvell International Ltd.
 *
 * SPDX-License-Identifier:     BSD-3-Clause
 * https://spdx.org/licenses
 */

#ifndef __OCTEONTX_SDEI_H__
#define __OCTEONTX_SDEI_H__

/* SDEI explicit private event numbers */
#define OCTEONTX_SDEI_RAS_MDC_EVENT		0x40000000
#define OCTEONTX_SDEI_RAS_MCC_EVENT		0x40000001
#define OCTEONTX_SDEI_RAS_LMC_EVENT		0x40000002

#define OCTEONTX_SDEI_PRIVATE_EVENTS \
	SDEI_DEFINE_EVENT_0(SDEI_SGI_IRQ), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_MDC_EVENT, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_MCC_EVENT, SDEI_MAPF_CRITICAL), \
	SDEI_EXPLICIT_EVENT(OCTEONTX_SDEI_RAS_LMC_EVENT, SDEI_MAPF_CRITICAL), \

#define OCTEONTX_SDEI_SHARED_EVENTS

#endif // __OCTEONTX_SDEI_H__
